# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Mobius Forensic Toolkit
# Copyright (C) 2008-2026 Eduardo Aguiar
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
import datetime
import os.path

import mobius
import pymobius
from gi.repository import GLib
from gi.repository import Gtk

from metadata import *


# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Report Generator view
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
class ReportGeneratorView(object):

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief Initialize widget
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def __init__(self):
        self.__mediator = pymobius.mediator.copy()
        self.__iped_path = None

        self.name = f'{EXTENSION_NAME} v{EXTENSION_VERSION}'
        icon_path = self.__mediator.call('extension.get-icon-path', EXTENSION_ID)
        self.icon_data = open(icon_path, 'rb').read()

        # vbox
        vbox = mobius.core.ui.box(mobius.core.ui.box.orientation_vertical)
        vbox.set_visible(True)
        self.__widget = vbox

        # Generate button
        self.__generate_button = mobius.core.ui.button()
        self.__generate_button.set_icon_by_name('list-add')
        self.__generate_button.set_text("_Add")
        self.__generate_button.set_visible(True)
        self.__generate_button.set_callback('clicked', self.__on_generate_report)
        vbox.add_child(self.__generate_button, mobius.core.ui.box.fill_none)
        
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief Get ui widget
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def get_ui_widget(self):
        return self.__widget.get_ui_widget()

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief Set status text
    # @param text Text
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def set_status(self, text):
        if text:
            t = str(datetime.datetime.now())[:19]
            text = t + ' ' + text

        GLib.idle_add(self.__status_label.set_text, text or '')

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief set data to be viewed
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def set_data(self, itemlist):
        self.__itemlist = itemlist

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief Set IPED path
    # @param path Full path
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def set_iped_path(self, path):
        self.__iped_path = path

        self.__processing_view.set_iped_path(path)
        self.__report_view.set_iped_path(path)
        self.__preferences_view.set_iped_path(path)

        if not path:
            self.__view_selector.set_current_view('preferences')

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief on_destroy view
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def on_destroy(self):
        self.__mediator.clear()

    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    # @brief on_generate_report button clicked
    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    def __on_generate_report(self):
        generate_report (self.__itemlist, '/home/aguiar/src/mobius-dev/beta/report/media.en_US.tailwind')

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Generate report
# @param itemlist List of items to be included in the report
# @param path Output path
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def generate_report(itemlist, path):

    items_js_path = os.path.join(path, 'data', 'items.js')

    f = mobius.core.io.new_file_by_path(items_js_path)
    fp = mobius.core.io.text_writer(f.new_writer())

    # Create data
    fp.write('// Generated by Mobius Forensic Toolkit\n')
    fp.write('// Warning: This file is automatically generated. Do not edit manually.\n')
    fp.write('\n')

    app = mobius.core.application()
    fp.write(f'window.VERSION = "{app.version}";\n')

    fp.write('\n')
    fp.write('const ITEMS = [\n')

    for item in itemlist:
        generate_item(item, fp)

    fp.write('];\n')
    fp.write('\n')
    fp.write('window.ITEMS = ITEMS;\n')

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Generate item
# @param item Item
# @param fp File pointer
# @param parent Parent item
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def generate_item(item, fp, parent=None):
    fp.write('  {\n')
    fp.write(f'    uid: {item.uid},\n')
    fp.write(f'    name: "{item.name}",\n')

    # Metadata
    fp.write('    metadata: [\n')
    category = mobius.framework.get_category(item.category)

    for attr in category.get_attributes():
        if attr.name and attr.name[0].islower():
            name = attr.name[0].upper() + attr.name[1:]
        else:
            name = attr.name

        if attr.id == 'uid':
            value = item.uid

        elif attr.id == 'category':
            value = item.category

        else:
            value = item.get_attribute(attr.id)

        if value is None:
            value = ''

        fp.write(f'      {{ id: "{attr.id}", name: "{name}", value: "{value}" }},\n')

    fp.write('    ],\n')

    # Parent item
    if parent:
        fp.write(f'    parent: {parent.uid},\n')
    else:
        fp.write('    parent: null,\n')

    # Children items
    fp.write (f'    children: [{", ".join(str(child.uid) for child in item.get_children())}],\n')

    # Datasource data
    datasource = item.get_datasource()

    if datasource:
        if datasource.get_type() == 'vfs':
            generate_vfs(datasource, fp)

        elif datasource.get_type() == 'ufdr':
            generate_ufdr(datasource, fp)

    # Finish item
    fp.write('  },\n')

    # Generate children items
    for child in item.get_children():
        generate_item(child, fp, item)


# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Generate VFS data
# @param datasource Datasource object
# @param fp Writer object
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def generate_vfs(datasource, fp):
    vfs = datasource.get_vfs()
    fp.write('    vfs: {\n')
    fp.write('      blocks: [\n')

    for block in vfs.get_blocks():
        fp.write('      {\n')
        fp.write(f'        id: {block.uid},\n')
        fp.write(f'        type: "{block.type}",\n')
        fp.write(f'        size: {block.size},\n')
        fp.write(f'        description: "{block.get_attribute("description")}",\n')
        fp.write(f'        parents: [{", ".join(str(parent.uid) for parent in block.get_parents())}],\n')
        fp.write('        metadata: [\n')

        for name, value in block.get_attributes().get_values():
            name = name.replace('_', ' ').capitalize()
            fp.write(f'          {{ name: "{name}", value: "{value}" }},\n')
        fp.write('        ],\n')

        fp.write('      },\n')

    fp.write('    ]\n')
    fp.write('  },\n')


# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Generate UFDR data
# @param datasource Datasource object
# @param fp Writer object
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def generate_ufdr(datasource, fp):
    fp.write('    ufdr: [\n')

    # Case info
    case_info = datasource.get_case_info()
    fp.write ('      { type: "case_info", description: "Case information", metadata: [\n')

    for name, value in case_info.get_values():
        name = name.replace('_', ' ').capitalize()
        fp.write(f'        {{ name: "{name}", value: "{value}" }},\n')
    fp.write('        ]\n')
    fp.write('      },\n')

    # Extractions
    for e in datasource.get_extractions():
        fp.write(f'      {{ type: "extraction", name: "{e.name}", metadata: [\n')

        fp.write(f'        {{ name: "ID", value: "{e.id}" }},\n')
        fp.write(f'        {{ name: "Type", value: "{e.type}" }},\n')
        fp.write(f'        {{ name: "Name", value: "{e.name}" }},\n')
        fp.write(f'        {{ name: "Device Name", value: "{e.device_name}" }},\n')

        for name, value in e.get_metadata():
            fp.write(f'        {{ name: "{name}", value: "{value}" }},\n')

        fp.write('        ]\n')
        fp.write('      },\n')

    fp.write('    ],\n')

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Start function
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def pvt_start():
    mobius.core.add_resource('view.report-generator', 'Report Generator view', ReportGeneratorView)


# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# @brief Stop function
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
def pvt_stop():
    mobius.core.remove_resource('view.report-generator')
